name: Continuous Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run your bot
        run: |
          # Your bot start command here
          node index.js
